disabled_rules: # rule identifiers to exclude from running
    - line_length
    - trailing_whitespace
    - identifier_name
    - explicit_type_interface
    - sorted_imports
    - todo
    - implicit_getter

opt_in_rules: # some rules are only opt-in
    - attributes
    - closure_end_indentation
    - conditional_returns_on_newline
    - empty_count
    - literal_expression_end_indentation
    - object_literal
    - operator_usage_whitespace
    - redundant_nil_coalescing
    - unneeded_parentheses_in_closure_argument
    - control_statement
    - trailing_newline
    - colon
    - comma
    
type_name:
    allowed_symbols: "_"
    
excluded:
    - Pods
    - ItunesvipTests
    - ItunesvipUITests

# configurable rules can be customized from this configuration file
# Complexity of function bodies should be limited.
cyclomatic_complexity: 25
force_cast:
    severity: warning # explicitly
force_try:
    severity: warning # explicitly
large_tuple: 3
function_parameter_count: 5
type_body_length:
    - 200 # warning
    - 300 # error
file_length:
    warning: 700
    error: 900
function_body_length: 80
reporter: 'xcode'
